server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #mapper.xml文件地址
  configuration:
    map-underscore-to-camel-case: true   #驼峰命名


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/gmall-study?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      max-active: 20
      max-wait: 5000
      initial-size: 2
      validationQuery: SELECT 'x'   #验证连接
      enable: true
